image:
  file: .gitpod.Dockerfile
tasks:
- init: >
    python3 -m pip install -e .[develop]
  command: >
    python3.8 setup.py test
github:
    prebuilds:
        pullRequestsFromForks: true
vscode:
  extensions:
    - BazelBuild.vscode-bazel@0.4.0:CNqPe08EnThWfsQXBuinsQ==
