image:
  file: .gitpod.Dockerfile
tasks:
- init: >
    python --version
  command: >
    python setup.py test
github:
    prebuilds:
        pullRequestsFromForks: true
vscode:
  extensions:
    - BazelBuild.vscode-bazel@0.4.0:CNqPe08EnThWfsQXBuinsQ==
